name: check_formatting

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  check_formatting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check formatting
      run: cargo fmt --all -- --check
